const initialState = [
    {
        position: 0,
        currentValue: 0,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 1,
        currentValue: 1,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 2,
        currentValue: 2,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 3,
        currentValue: 3,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 4,
        currentValue: 4,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 5,
        currentValue: 5,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 6,
        currentValue: 6,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 7,
        currentValue: 7,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 8,
        currentValue: 8,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 9,
        currentValue: 9,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 10,
        currentValue: 10,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 11,
        currentValue: 11,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 12,
        currentValue: 12,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 13,
        currentValue: 13,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 14,
        currentValue: 14,
        up: false,
        down: false,
        left: false,
        right: false,
    },
    {
        position: 15,
        currentValue: null,
        up: false,
        down: false,
        left: false,
        right: false,
    }
]

export default initialState;